import type { Metadata } from "next";
import "./globals.css";
<<<<<<< HEAD


export const metadata: Metadata = {
  title: "StockUp",
  description: "Generated by create next app",
=======
import Link from "next/link";


export const metadata: Metadata = {
  title: "Stockup",
  description: "Your stock trading app",
>>>>>>> 0ee5324 (update some pages)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"font-sans antialiased"}
      >
        {children}
<<<<<<< HEAD
=======
        <footer className="bg-[#949494] py-4">
          <ul className="flex justify-center flex-col md:flex-row gap-3 md:gap-5 text-center">
            <li className="text-sm">
              <Link className="hover:underline" href="/">
                Privacy Policy
              </Link>
            </li>
            <li className="text-sm">
              <Link className="hover:underline" href="/">
                Terms of Service
              </Link>
            </li>
            <li className="text-sm">
              <Link className="hover:underline" href="/">
                Help
              </Link>
            </li>
          </ul>
        </footer>
>>>>>>> 0ee5324 (update some pages)
      </body>
    </html>
  );
}
